[package]
name = "RustStuff"
version = "0.1.0"
authors = ["ClemensFMN <clemens@familie-novak.net>"]

[dependencies]
rand="0.3.0"
serde="1.0.15"
serde_derive="1.0"
serde_json="1.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
